defaults:
  - /llm@plan_config.llm: EXAMPLE
  - /instruct@plan_config.instruct: EXAMPLE_few_shot_centralized_motoronly

_target_: 'habitat_llm.planner.CentralizedLLMPlanner'
_recursive_: False
_partial_: True

plan_config:
    replanning_threshold: 100
    max_consecutive_identical_joint_actions: 5
    planning_mode: "cot"
    constrained_generation: True
    objects_response: True
    objects_response_include_states: False
    example_type: "react"
    centralized: True
